# Generated by Django 5.0.4 on 2024-05-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Dish',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
